style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: ""
options:
  commits:
    filters:
#      Type:
#        - fix
#        - perf
#        - refactor
#        - ci
  commit_groups:
    title_maps:
#      feat: Features
#      fix: Bug Fixes
#      perf: Performance Improvements
#      refactor: Code Refactoring
#      ci: CI
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
